on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn
      - run: yarn build

      - run: yarn pack --filename build.tar.gz

      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build

      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: mock-package

      - run: |
          mv build.tar.gz ${{ steps.release.outputs.tag_name }}.tar.gz
          rm -rf build.tar.gz
        if: ${{ steps.release.outputs.release_created }}

      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release upload ${{ steps.release.outputs.tag_name }} ${{ steps.release.outputs.tag_name }}.tar.gz
